<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

/**  @var array $modversion */
$modversion['name']           = _MI_COUNTDOWN_NAME;
$modversion['version']        = '0.3';
$modversion['module_status']  = 'Alpha 1';
$modversion['release_date']   = '2020/04/30';
$modversion['description']    = _MI_COUNTDOWN_DESC;
$modversion['credits']        = 'Eric Juden (ejuden01)';
$modversion['author']         = 'Alan Juden (ajuden)';
$modversion['help']           = 'not yet';
$modversion['license']        = 'GPL see LICENSE';
$modversion['license_url']    = 'www.gnu.org/licenses/gpl-2.0.html';
$modversion['official']       = 0;
$modversion['image']          = 'assets/images/logoModule.png';
$modversion['dirname']        = 'countdown';

//About
$modversion['module_website_url']  = 'https://xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['min_php']             = '5.6';
$modversion['min_xoops']           = '2.5.10';
$modversion['min_admin']           = '1.2';
$modversion['min_db']              = array('mysql' => '5.5', 'mysqli' => '5.5');

// Install, update, unistall
$modversion['onInstall']   = 'include/oninstall.php';
$modversion['onUpdate']    = 'include/onupdate.php';
$modversion['onUninstall'] = 'include/onuninstall.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'countdown_events';

// Templates
$modversion['templates'] = [
    ['file'        => 'countdown_index.tpl',
     'description' => _MI_CD_TEMP_COUNTDOWN],
    ['file'        => 'countdown_add.tpl',
     'description' => _MI_CD_TEMP_COUNTDOWN_ADD],
    ['file'        => 'countdown_edit.tpl',
     'description' => _MI_CD_TEMP_COUNTDOWN_EDIT]
];

// Menu - only show for registered XOOPS users
if ($GLOBALS['xoopsUser'] instanceof \XoopsUser) {
    $modversion['hasMain']        = 1;
    $modversion['sub'] = [
        ['name' => _MI_MENU_ADD_NEW,
         'url'  => 'index.php?op=add'],
        ['name' => _MI_MENU_VIEW_ALL,
         'url'  => 'index.php?op=all'],
        ['name' => _MI_MENU_VIEW_CURRENT,
         'url'  => 'index.php'],
        ['name' => _MI_MENU_VIEW_EXPIRED,
         'url'  => 'index.php?op=expired']
    ];
} else {
    $modversion['hasMain'] = 0;
}

// Disabled XOOPS features
$modversion['hasAdmin']        = 0;
$modversion['hasSearch']       = 0;
$modversion['hasComments']     = 0;
$modversion['hasNotification'] = 0;
